from typing import Any, Protocol


class ConfigStore(Protocol):
    def read(self) -> dict[str, Any]: ...

    def write(self, config: dict[str, Any]) -> None: ...

    def get(self, key: str) -> Any: ...

    def set(self, key: str, value: Any) -> None: ...
